---
swagger: "2.0"
info:
  description: |-
    # Introduction
    What does your API do?

    # Overview
    Things that the developers should know about

    # Authentication
    What is the preferred way of using the API?

    # Error Codes
    What errors and status codes can a user expect?

    # Rate limit
    Is there a limit to the number of requests an user can send?
definitions: {}
